appname = api_mid_beego_request
httpport = 8090
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true

ProtocolAdmin=${API_MID_BEEGO_REQUEST_PROTOCOL_ADMIN}
UrlCrudParametros=${API_MID_BEEGO_REQUEST_PARAMETROS_URL}
UrlCrudResoluciones=${API_MID_BEEGO_REQUEST_RESOLUCIONES_URL}
